<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Boning;
use App\Models\BoningItem;
use App\Models\Grade;
use App\Models\Warehouse;
use App\Models\Product;
use App\Models\BeefStock;
use App\Models\BeefStockMovement;
use App\Models\Customer;
use App\Models\CustomerSegment;
use App\Models\SalesOrder;
use App\Models\Tally;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Livewire\Livewire;
use App\Filament\Admin\Resources\BoningResource\Pages\LabelingBoning;

class BoningTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        // Seed basic grades and warehouses
        Warehouse::create(['code' => 'JONGGOL', 'name' => 'JONGGOL', 'is_active' => true]);
        Warehouse::create(['code' => 'PERUM', 'name' => 'PERUM', 'is_active' => true]);

        Grade::create(['name' => 'CHILL', 'is_active' => true]);
        Grade::create(['name' => 'FROZEN', 'is_active' => true]);
        Grade::create(['name' => 'A', 'is_active' => true]);
    }

    /** @test */
    public function it_creates_a_boning_batch_with_autogenerated_doc_no()
    {
        $user = User::factory()->create();

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'note' => 'Test Batch Note',
            'created_by' => $user->id,
        ]);

        $yearStr = date('y');
        $expectedDocNo = 'BN' . $yearStr . '001';
        $this->assertEquals($expectedDocNo, $boning->doc_no);
        $this->assertEquals('OPEN', $boning->status);
    }

    /** @test */
    public function it_allows_authenticated_user_to_view_printed_boning_label()
    {
        $user = User::factory()->create();

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $category = \App\Models\ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $warehouse = Warehouse::where('code', 'JONGGOL')->first();
        $grade = Grade::where('name', 'CHILL')->first();

        $item = BoningItem::create([
            'boning_id' => $boning->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'barcode' => '1100626B001112550355001',
            'created_by' => $user->id,
        ]);

        $response = $this->actingAs($user)
            ->get(route('boning.label', $item->id));

        $response->assertStatus(200);
        $response->assertSee('PT. SANTI WIJAYA MEAT');
        $response->assertSee('SIRLOIN BEEF');
        $response->assertSee('12.55');
        $response->assertSee('3-Pcs');
        $response->assertSee('1100626B001112550355001');
    }

    /** @test */
    public function it_shows_delete_action_when_boning_item_is_not_in_repack_materials()
    {
        $user = User::factory()->create(['role' => 'programmer', 'is_active' => true]);

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $category = \App\Models\ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $warehouse = Warehouse::where('code', 'JONGGOL')->first();
        $grade = Grade::where('name', 'CHILL')->first();

        $item = BoningItem::create([
            'boning_id' => $boning->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'barcode' => '1100626B001112550355001',
            'created_by' => $user->id,
        ]);

        Livewire::actingAs($user)
            ->test(LabelingBoning::class, ['record' => $boning])
            ->assertTableActionVisible('delete', $item)
            ->assertTableActionHidden('repack_status', $item);
    }

    /** @test */
    public function it_hides_delete_action_and_shows_repack_status_action_when_item_is_in_repack_materials()
    {
        $user = User::factory()->create(['role' => 'programmer', 'is_active' => true]);

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $repack = \App\Models\Repack::create([
            'repack_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $category = \App\Models\ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $warehouse = Warehouse::where('code', 'JONGGOL')->first();
        $grade = Grade::where('name', 'CHILL')->first();

        $item = BoningItem::create([
            'boning_id' => $boning->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'barcode' => '1100626B001112550355001',
            'created_by' => $user->id,
        ]);

        // Insert into repack_materials to simulate being in repack
        \Illuminate\Support\Facades\DB::table('repack_materials')->insert([
            'repack_id' => $repack->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'barcode' => '1100626B001112550355001',
            'weight' => 12.55,
            'qty_pcs' => 3,
            'pack_date' => now()->format('Y-m-d'),
            'exp_date' => now()->addMonths(3)->format('Y-m-d'),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Livewire::actingAs($user)
            ->test(LabelingBoning::class, ['record' => $boning])
            ->assertTableActionHidden('delete', $item)
            ->assertTableActionVisible('repack_status', $item);
    }

    /** @test */
    public function it_hides_delete_action_and_shows_tally_status_action_when_item_is_in_tally_items()
    {
        $user = User::factory()->create(['role' => 'programmer', 'is_active' => true]);

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $segment = CustomerSegment::create([
            'name' => 'RETAIL',
            'is_active' => true,
        ]);

        $customer = Customer::create([
            'name' => 'BLACK OWL',
            'customer_segment_id' => $segment->id,
            'address' => 'Ruko PIK',
            'pic' => 'John Doe',
            'phone' => '0812345678',
            'top' => 30,
        ]);

        $so = SalesOrder::create([
            'customer_id' => $customer->id,
            'delivery_date' => now()->addDays(2)->format('Y-m-d'),
            'po_number' => 'PO12345',
            'created_by' => $user->id,
            'status' => 'processing',
        ]);

        $tally = Tally::create([
            'sales_order_id' => $so->id,
            'status' => 'processing',
        ]);

        $category = \App\Models\ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $warehouse = Warehouse::where('code', 'JONGGOL')->first();
        $grade = Grade::where('name', 'CHILL')->first();

        $item = BoningItem::create([
            'boning_id' => $boning->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'barcode' => '1100626B001112550355001',
            'created_by' => $user->id,
        ]);

        // Insert into tally_items
        \App\Models\TallyItem::create([
            'tally_id' => $tally->id,
            'barcode' => '1100626B001112550355001',
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'origin' => 'BONING',
        ]);

        Livewire::actingAs($user)
            ->test(LabelingBoning::class, ['record' => $boning])
            ->assertTableActionHidden('delete', $item)
            ->assertTableActionVisible('tally_status', $item);
    }
}
