<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Boning;
use App\Models\BoningItem;
use App\Models\Grade;
use App\Models\Warehouse;
use App\Models\Product;
use App\Models\BeefStock;
use App\Models\BeefStockMovement;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BoningTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        // Seed basic grades and warehouses
        Warehouse::create(['code' => 'JONGGOL', 'name' => 'JONGGOL', 'is_active' => true]);
        Warehouse::create(['code' => 'PERUM', 'name' => 'PERUM', 'is_active' => true]);

        Grade::create(['name' => 'CHILL', 'is_active' => true]);
        Grade::create(['name' => 'FROZEN', 'is_active' => true]);
        Grade::create(['name' => 'A', 'is_active' => true]);
    }

    /** @test */
    public function it_creates_a_boning_batch_with_autogenerated_doc_no()
    {
        $user = User::factory()->create();

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'note' => 'Test Batch Note',
            'created_by' => $user->id,
        ]);

        $yearStr = date('y');
        $expectedDocNo = 'BN' . $yearStr . '001';
        $this->assertEquals($expectedDocNo, $boning->doc_no);
        $this->assertEquals('OPEN', $boning->status);
    }

    /** @test */
    public function it_allows_authenticated_user_to_view_printed_boning_label()
    {
        $user = User::factory()->create();

        $boning = Boning::create([
            'boning_date' => now()->format('Y-m-d'),
            'created_by' => $user->id,
        ]);

        $category = \App\Models\ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $warehouse = Warehouse::where('code', 'JONGGOL')->first();
        $grade = Grade::where('name', 'CHILL')->first();

        $item = BoningItem::create([
            'boning_id' => $boning->id,
            'product_id' => $product->id,
            'warehouse_id' => $warehouse->id,
            'grade_id' => $grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
            'barcode' => '1100626B001112550355001',
            'created_by' => $user->id,
        ]);

        $response = $this->actingAs($user)
            ->get(route('boning.label', $item->id));

        $response->assertStatus(200);
        $response->assertSee('PT. SANTI WIJAYA MEAT');
        $response->assertSee('SIRLOIN BEEF');
        $response->assertSee('12.55');
        $response->assertSee('3-Pcs');
        $response->assertSee('1100626B001112550355001');
    }
}
