<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Repack;
use App\Models\RepackMaterial;
use App\Models\RepackResult;
use App\Models\Grade;
use App\Models\Warehouse;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\BeefStock;
use App\Models\BeefStockMovement;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Livewire\Livewire;
use App\Filament\Admin\Resources\RepackResource\Pages\InputBahanRepack;
use App\Filament\Admin\Resources\RepackResource\Pages\InputHasilRepack;
use Carbon\Carbon;

class RepackTest extends TestCase
{
    use RefreshDatabase;

    protected User $user;
    protected Warehouse $warehouse;
    protected Grade $grade;
    protected Product $product;
    protected Repack $repack;

    protected function setUp(): void
    {
        parent::setUp();

        // Create user with 'programmer' role so that hasPermission() always returns true
        $this->user = User::factory()->create([
            'role' => 'programmer',
            'is_active' => true
        ]);

        // Seed basic grades and warehouses
        $this->warehouse = Warehouse::create(['code' => 'JONGGOL', 'name' => 'JONGGOL', 'is_active' => true]);
        Warehouse::create(['code' => 'PERUM', 'name' => 'PERUM', 'is_active' => true]);

        $this->grade = Grade::create(['name' => 'CHILL', 'is_active' => true]);
        Grade::create(['name' => 'FROZEN', 'is_active' => true]);

        $category = ProductCategory::create([
            'name' => 'MEAT',
            'prefix' => 'MT',
            'is_active' => true,
        ]);

        $this->product = Product::create([
            'name' => 'SIRLOIN BEEF',
            'code' => 'B001',
            'category_id' => $category->id,
            'structure_type' => 'main',
            'is_active' => true,
        ]);

        $this->repack = Repack::create([
            'repack_date' => now()->format('Y-m-d'),
            'note' => 'Test Repack Batch',
            'created_by' => $this->user->id,
        ]);
    }

    /** @test */
    public function it_creates_a_repack_batch_with_autogenerated_doc_no()
    {
        $yearStr = date('y');
        $expectedDocNo = 'RP#' . $yearStr . '001';
        $this->assertEquals($expectedDocNo, $this->repack->doc_no);
        $this->assertEquals('OPEN', $this->repack->status);
    }

    /** @test */
    public function it_can_scan_bahan_completely_and_then_void_it_back_to_stock_exactly()
    {
        // 1. Create a stock
        $barcode = '1260626B001112550355001';
        $stock = BeefStock::create([
            'barcode' => $barcode,
            'product_id' => $this->product->id,
            'warehouse_id' => $this->warehouse->id,
            'grade_id' => $this->grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => '2026-06-01',
            'exp_date' => '2026-09-01',
            'origin' => 'BONING',
            'status' => 'IN_STOCK',
        ]);

        // 2. Scan barcode using InputBahanRepack page component
        Livewire::actingAs($this->user)
            ->test(InputBahanRepack::class, ['record' => $this->repack])
            ->set('data.barcode', $barcode)
            ->call('submitBarcode')
            ->assertHasNoErrors();

        // Verify stock is removed from beef_stocks
        $this->assertDatabaseMissing('beef_stocks', ['barcode' => $barcode]);

        // Verify repack material is created with full stock details
        $material = RepackMaterial::where('barcode', $barcode)->firstOrFail();
        $this->assertEquals($this->repack->id, $material->repack_id);
        $this->assertEquals($barcode, $material->barcode);
        $this->assertEquals($this->product->id, $material->product_id);
        $this->assertEquals($this->warehouse->id, $material->warehouse_id);
        $this->assertEquals($this->grade->id, $material->grade_id);
        $this->assertEquals(12.55, $material->weight);
        $this->assertEquals(3, $material->qty_pcs);
        $this->assertEquals(5.5, $material->ph_level);
        $this->assertEquals('2026-06-01', Carbon::parse($material->pack_date)->format('Y-m-d'));
        $this->assertEquals('2026-09-01', Carbon::parse($material->exp_date)->format('Y-m-d'));
        $this->assertEquals('BONING', $material->origin);
        $this->assertEquals('IN_STOCK', $material->status);

        // Verify stock movement OUT_TO_REPACK is created
        $this->assertDatabaseHas('beef_stock_movements', [
            'product_id' => $this->product->id,
            'warehouse_id' => $this->warehouse->id,
            'barcode' => $barcode,
            'transaction_type' => 'OUT_TO_REPACK',
            'reference_document' => $this->repack->doc_no,
            'weight_out' => 12.55,
            'pcs_out' => 3,
        ]);

        // 3. Now let's void/delete the material
        Livewire::actingAs($this->user)
            ->test(InputBahanRepack::class, ['record' => $this->repack])
            ->callTableAction('delete', $material);

        // Verify repack material is deleted
        $this->assertDatabaseMissing('repack_materials', ['barcode' => $barcode]);

        // Verify stock is returned to beef_stocks with exact original values
        $this->assertDatabaseHas('beef_stocks', [
            'barcode' => $barcode,
            'product_id' => $this->product->id,
            'warehouse_id' => $this->warehouse->id,
            'grade_id' => $this->grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'origin' => 'BONING',
            'status' => 'IN_STOCK',
        ]);
        
        $returnedStock = BeefStock::where('barcode', $barcode)->firstOrFail();
        $this->assertEquals('2026-06-01', Carbon::parse($returnedStock->pack_date)->format('Y-m-d'));
        $this->assertEquals('2026-09-01', Carbon::parse($returnedStock->exp_date)->format('Y-m-d'));

        // Verify stock movement VOID_OUT_REPACK is created
        $this->assertDatabaseHas('beef_stock_movements', [
            'product_id' => $this->product->id,
            'warehouse_id' => $this->warehouse->id,
            'barcode' => $barcode,
            'transaction_type' => 'VOID_OUT_REPACK',
            'weight_in' => 12.55,
            'pcs_in' => 3,
        ]);
    }

    /** @test */
    public function it_can_input_hasil_repack_and_then_void_it_properly()
    {
        // 1. Fill input hasil repack form using InputHasilRepack component manually
        Livewire::actingAs($this->user)
            ->test(InputHasilRepack::class, ['record' => $this->repack])
            ->set('data.origin', '2')
            ->set('data.product_id', $this->product->id)
            ->set('data.grade_id', $this->grade->id)
            ->set('data.pack_date', '2026-06-10')
            ->set('data.exp_date', '2026-09-10')
            ->set('data.qty_pcs_combined', '10.50/2')
            ->set('data.ph_level', 5.5)
            ->set('data.show_exp', true)
            ->call('create')
            ->assertHasNoErrors();

        // Check repack results exists
        $result = RepackResult::firstOrFail();
        $this->assertEquals($this->repack->id, $result->repack_id);
        $this->assertEquals(10.50, $result->weight);
        $this->assertEquals(2, $result->qty_pcs);
        $this->assertEquals(5.5, $result->ph_level);
        $this->assertNotEmpty($result->barcode);

        // Verify stock is created in beef_stocks
        $this->assertDatabaseHas('beef_stocks', [
            'barcode' => $result->barcode,
            'product_id' => $this->product->id,
            'warehouse_id' => 1,
            'grade_id' => $this->grade->id,
            'weight' => 10.50,
            'qty_pcs' => 2,
            'ph_level' => 5.5,
            'origin' => 'REPACK',
            'status' => 'IN_STOCK',
        ]);

        // Verify stock movement IN_REPACK is created
        $this->assertDatabaseHas('beef_stock_movements', [
            'product_id' => $this->product->id,
            'warehouse_id' => 1,
            'barcode' => $result->barcode,
            'transaction_type' => 'IN_REPACK',
            'reference_document' => $this->repack->doc_no,
            'weight_in' => 10.50,
            'pcs_in' => 2,
        ]);

        // 2. Let's void the result
        Livewire::actingAs($this->user)
            ->test(InputHasilRepack::class, ['record' => $this->repack])
            ->callTableAction('delete', $result);

        // Verify repack result is soft deleted or removed
        $this->assertSoftDeleted('repack_results', ['id' => $result->id]);

        // Verify stock is removed from beef_stocks
        $this->assertDatabaseMissing('beef_stocks', ['barcode' => $result->barcode]);

        // Verify stock movement VOID_IN_REPACK is created (negative weight_in/pcs_in)
        $this->assertDatabaseHas('beef_stock_movements', [
            'product_id' => $this->product->id,
            'warehouse_id' => 1,
            'barcode' => $result->barcode,
            'transaction_type' => 'VOID_IN_REPACK',
            'weight_in' => -10.50,
            'pcs_in' => -2,
        ]);
    }

    /** @test */
    public function it_renders_repack_printed_label_and_summary_page()
    {
        // Create a result item for printing label
        $result = RepackResult::create([
            'repack_id' => $this->repack->id,
            'product_id' => $this->product->id,
            'warehouse_id' => 1,
            'grade_id' => $this->grade->id,
            'barcode' => '2260626B001112550355001',
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => now(),
            'exp_date' => now()->addMonths(3),
        ]);

        // Access printed label
        $response = $this->actingAs($this->user)
            ->get(route('repack.label', ['id' => $result->id, 'show_exp' => 1]));

        $response->assertStatus(200);
        $response->assertSee('PT. SANTI WIJAYA MEAT');
        $response->assertSee('SIRLOIN BEEF');
        $response->assertSee('12.55');
        $response->assertSee('2260626B001112550355001');

        // Access printed summary
        $responseSummary = $this->actingAs($this->user)
            ->get(route('repack.summary', ['id' => $this->repack->id]));

        $responseSummary->assertStatus(200);
        $responseSummary->assertSee('LAPORAN PRODUKSI REPACK');
        $responseSummary->assertSee($this->repack->doc_no);
    }

    /** @test */
    public function it_prevents_adding_bahan_and_hasil_and_hides_actions_when_repack_is_locked()
    {
        // 1. Lock the repack
        $this->repack->update(['kunci' => 1]);

        // 2. Create stock
        $barcode = '1260626B001112550355001';
        BeefStock::create([
            'barcode' => $barcode,
            'product_id' => $this->product->id,
            'warehouse_id' => $this->warehouse->id,
            'grade_id' => $this->grade->id,
            'weight' => 12.55,
            'qty_pcs' => 3,
            'ph_level' => 5.5,
            'pack_date' => '2026-06-01',
            'exp_date' => '2026-09-01',
            'origin' => 'BONING',
            'status' => 'IN_STOCK',
        ]);

        // Attempt scanning barcode on locked repack should fail
        Livewire::actingAs($this->user)
            ->test(InputBahanRepack::class, ['record' => $this->repack])
            ->set('data.barcode', $barcode)
            ->call('submitBarcode')
            ->assertHasNoErrors();

        // Verify stock is STILL in beef_stocks (not scanned because locked)
        $this->assertDatabaseHas('beef_stocks', ['barcode' => $barcode]);

        // Attempt creating hasil repack on locked repack should fail
        Livewire::actingAs($this->user)
            ->test(InputHasilRepack::class, ['record' => $this->repack])
            ->set('data.origin', '2')
            ->set('data.product_id', $this->product->id)
            ->set('data.grade_id', $this->grade->id)
            ->set('data.pack_date', '2026-06-10')
            ->set('data.exp_date', '2026-09-10')
            ->set('data.qty_pcs_combined', '10.50/2')
            ->set('data.ph_level', 5.5)
            ->set('data.show_exp', true)
            ->call('create');

        // Verify no repack result was created
        $this->assertDatabaseEmpty('repack_results');
    }

    /** @test */
    public function it_shows_pending_repack_lock_count_on_dashboard_widget_for_authorized_users()
    {
        // 1. Create a few repacks, some locked and some unlocked
        // $this->repack is already created in setUp (unlocked, so 1 unlocked repack)
        
        $lockedRepack = Repack::create([
            'repack_date' => now()->format('Y-m-d'),
            'note' => 'Locked Batch',
            'created_by' => $this->user->id,
            'kunci' => 1,
        ]);

        // 2. Create standard user with lock_repacks permission
        $userWithPerm = User::factory()->create([
            'role' => 'employee',
            'is_active' => true
        ]);
        $permission = \App\Models\Permission::create([
            'name' => 'lock_repacks',
            'module_name' => 'Repack',
            'description' => 'Lock/Unlock repack batch'
        ]);
        $userWithPerm->permissions()->attach($permission->id);

        // 3. Create user without permission
        $userWithoutPerm = User::factory()->create([
            'role' => 'employee',
            'is_active' => true
        ]);

        // Test with authorized user
        Livewire::actingAs($userWithPerm)
            ->test(\App\Filament\Admin\Widgets\PendingTaskWidget::class)
            ->assertSee('repack yang belum dikunci');

        // Test widget directly using helper methods
        $widget = new \App\Filament\Admin\Widgets\PendingTaskWidget();

        $this->actingAs($userWithPerm);
        $this->assertEquals(1, $widget->getPendingRepackLockCount());

        $this->actingAs($userWithoutPerm);
        $this->assertEquals(0, $widget->getPendingRepackLockCount());

        $this->actingAs($this->user); // Superuser / Programmer
        $this->assertEquals(1, $widget->getPendingRepackLockCount());
    }
}
